image: miniurl
imagePullPolicy: Always
port: 80
baseRedirectUrl: http://cp.aporia.local
url:
  matchPattern: '**'
  lifetime: '7 days'
ingress:
  enable: false
service:
  name:
storage:
  # InMemory or Relational
  driver: Relational
  deploy: true
  # If deploy is false, you should supply your own database credentials. the values correspond to a Knex.js config.
  relationalConfig:
    # See examples here: http://knexjs.org/#Installation-client
    # See the Typescript type here: http://knexjs.org/#Installation-client
    client:
    host:
    database:
    user:
    secrets:
      password:
container:
  image: miniservices/miniurl:v0.1.14
