baseRedirectUrl: https://my-short-base.url
storage:
    deploy: false
    relationalConfig:
        client: postgres
        host: localhost
        user: postgres
        database: postgres
        secrets:
            password: postgres
