baseRedirectUrl: https://my-short-base.url
storage:
    deploy: false
    driver: Relational
    relationalConfig:
        client: postgres
        host: localhost
        database: postgres
        user: postgres
        secrets:
            password: postgres
