{{ if .Values.ingress.enable }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "miniurl.appName" . }}-ingress
spec:
  rules:
    - host: "{{ first (regexSplit ":+" ((urlParse .Values.baseRedirectUrl).host) -1) }}"
      http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ template "miniurl.serviceName" . }}
              port:
                number: 80
    - http:
        paths:
        - path: /miniurl
          pathType: Prefix
          backend:
            service:
              name: {{ include "miniurl.serviceName" . }}
              port:
                number: 80
{{ end }}