apiVersion: v1
kind: Service
metadata:
  name: {{ include "miniurl.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "miniurl.appName" . }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http
      port: {{ .Values.port }}
  selector:
    app: {{ include "miniurl.appName" . }}
