name: Deploy Persistent Environment
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (demo)'     
        required: true
        default: demo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: make install-deps
      
      - name: Deploy
        run: make deploy
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
