name: Deploy Environment
on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment (demo)'     
        required: true
        default: demo
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ github.ref }}

      - name: Install dependencies
        run: make install-dependencies

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Deploy
        run: make deploy
        env:
          ENVIRONMENT: ${{ github.event.inputs.environment }}
